### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by nschloe** [inducer/meshpy#58]
The following piece of code segfaults for me. Not sure if I did anything wrong, but in any case a segfault should never happen.
```python
import math
from meshpy.geometry import (
    EXT_OPEN,
    GeometryBuilder,
    generate_surface_of_revolution,
)
from meshpy.tet import MeshInfo, build


h = 0.02
r = 3.0
polar_subdivision = int(math.pi / h)
dphi = math.pi / polar_subdivision


def truncate(val):
    return 0 if abs(val) < 1e-10 else val


rz = [
    [truncate(r * math.sin(i * dphi)), r * math.cos(i * dphi)]
    for i in range(polar_subdivision + 1)
]

geob = GeometryBuilder()
radial_subdivision = int(2 * math.pi / h)
geob.add_geometry(
    *generate_surface_of_revolution(
        rz, closure=EXT_OPEN, radial_subdiv=radial_subdivision
    )
)

mesh_info = MeshInfo()
geob.set(mesh_info)

build(mesh_info)
```
```
[1]    2685424 segmentation fault (core dumped)  python3 v.py
```

**Comment by inducer** [comment]
I can reproduce this. The backtrace has this crashing deep inside of tetgen:
```
#0  0x00007fffb8ad31cf in tetgenmesh::flipnm(tetgenmesh::triface*, int, int, int, tetgenmesh::flipconstraints*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#1  0x00007fffb8ad3891 in tetgenmesh::removeedgebyflips(tetgenmesh::triface*, tetgenmesh::flipconstraints*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#2  0x00007fffb8ad4d12 in tetgenmesh::reduceedgesatvertex(double*, tetgenmesh::arraypool*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#3  0x00007fffb8ad81ca in tetgenmesh::removevertexbyflips(double*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#4  0x00007fffb8ae67b4 in tetgenmesh::lawsonflip3d(tetgenmesh::flipconstraints*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#5  0x00007fffb8aea6ad in tetgenmesh::splitsubface(tetgenmesh::face*, double*, double*, int, double*, int) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#6  0x00007fffb8aeaf31 in tetgenmesh::splittetrahedron(tetgenmesh::triface*, int, double*, int) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#7  0x00007fffb8aeb1eb in tetgenmesh::repairbadtets(int) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#8  0x00007fffb8aeb796 in tetgenmesh::delaunayrefinement() () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#9  0x00007fffb8afce65 in tetrahedralize(tetgenbehavior*, tetgenio*, tetgenio*, tetgenio*, tetgenio*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#10 0x00007fffb8a9e7e9 in (anonymous namespace)::tetrahedralizeWrapper(tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*) ()
   from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#11 0x00007fffb8aa2c5c in pybind11::cpp_function::initialize<void (*&)(tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*), void, tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, pybind11::arg, pybind11::arg, pybind11::arg_v>(void (*&)(tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*), void (*)(tetgenbehavior&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo&, (anonymous namespace)::tMeshInfo*), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, pybind11::arg const&, pybind11::arg const&, pybind11::arg_v const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) ()
   from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#12 0x00007fffb8a73a8a in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /home/andreas/src/meshpy/meshpy/_internals.cpython-38-x86_64-linux-gnu.so
#13 0x000000000052108c in cfunction_call_varargs (kwargs=0x0, args=(<Options at remote 0x7fffb8b79db0>, <MeshInfo at remote 0x7fffb7b48310>, <MeshInfo at remote 0x7fffc15a54f0>), 
    func=<built-in method tetrahedralize of PyCapsule object at remote 0x7fffb8b69420>) at ../Objects/call.c:742
#14 PyCFunction_Call (func=<built-in method tetrahedralize of PyCapsule object at remote 0x7fffb8b69420>, args=(<Options at remote 0x7fffb8b79db0>, <MeshInfo at remote 0x7fffb7b48310>, <MeshInfo at remote 0x7fffc15a54f0>), kwargs=0x0)
    at ../Objects/call.c:772
#15 0x0000000000510513 in _PyObject_MakeTpCall (callable=<built-in method tetrahedralize of PyCapsule object at remote 0x7fffb8b69420>, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>)
    at ../Include/internal/pycore_pyerrors.h:13
#16 0x000000000050ab23 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fffb7b491e8, callable=<built-in method tetrahedralize of PyCapsule object at remote 0x7fffb8b69420>) at ../Include/cpython/abstract.h:125
#17 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fffb7b491e8, callable=<built-in method tetrahedralize of PyCapsule object at remote 0x7fffb8b69420>) at ../Include/cpython/abstract.h:115
#18 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x923100) at ../Python/ceval.c:4963
#19 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3469
#20 0x000000000051ad20 in PyEval_EvalFrameEx (throwflag=0, 
    f=Frame 0x7fffb7b49040, for file /home/andreas/src/meshpy/meshpy/tet.py, line 158, in tetrahedralize (mesh_info=<MeshInfo at remote 0x7fffb7b48310>, options=<Options at remote 0x7fffb8b79db0>, mesh=<MeshInfo at remote 0x7fffc15a54f0>, locale=<module at remote 0x7fffb8b79f90>, have_locale=True, prev_num_locale=(None, None))) at ../Python/ceval.c:741
#21 function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at ../Objects/call.c:283
#22 _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:410
#23 0x00000000005058a6 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fffb9067b50, callable=<function at remote 0x7fffb8b62040>) at ../Include/cpython/abstract.h:127
#24 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x923100) at ../Python/ceval.c:4963
#25 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3500
#26 0x0000000000503df5 in PyEval_EvalFrameEx (throwflag=0, 
    f=Frame 0x7fffb90679a0, for file /home/andreas/src/meshpy/meshpy/tet.py, line 186, in build (mesh_info=<MeshInfo at remote 0x7fffb7b48310>, options=<Options at remote 0x7fffb8b79db0>, verbose=False, attributes=False, volume_constraints=False, max_volume=None, diagnose=False, insert_points=None)) at ../Python/ceval.c:741
#27 _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x7ffff781d7b8, kwcount=<optimized out>, kwstep=1, 
    defs=0x7fffb8b56a78, defcount=7, kwdefs=0x0, closure=0x0, name='build', qualname='build') at ../Python/ceval.c:4298
#28 0x000000000051adae in _PyFunction_Vectorcall (func=<optimized out>, stack=0x7ffff781d7b0, nargsf=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:435
#29 0x00000000005058a6 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff781d7b0, callable=<function at remote 0x7fffb8b62af0>) at ../Include/cpython/abstract.h:127
#30 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x923100) at ../Python/ceval.c:4963
#31 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3500
#32 0x0000000000503df5 in PyEval_EvalFrameEx (throwflag=0, f=Frame 0x7ffff781d640, for file v.py, line 804, in <module> ()) at ../Python/ceval.c:741
#33 _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at ../Python/ceval.c:4298
#34 0x00000000005cd673 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=<optimized out>, globals=<optimized out>, _co=<optimized out>) at ../Python/ceval.c:4327
#35 PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:718
#36 0x00000000005eb6a1 in run_eval_code_obj (co=0x7ffff77e9ea0, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='v.py') at remote 0x7ffff7840160>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff78a70e0>, '__file__': 'v.py', '__cached__': None, 'math': <module at remote 0x7ffff774bb80>, 'EXT_OPEN': 0, 'GeometryBuilder': <type at remote 0xd1ccc0>, 'generate_surface_of_revolution': <function at remote 0x7fffb8b5dee0>, 'MeshInfo': <pybind11_type(__module__='meshpy.tet', set_facets=<function at remote 0x7fffb8b62700>, set_facets_ex=<function at remote 0x7fffb8b62790>, dump=<function at remote 0x7fffb8b62820>, write_vtk=<function at remote 0x7fffb8b628b0>, set_elements=<function at remote 0x7fffb8b62940>, set_element_constraints=<function at remote 0x7fffb8b629d0>, __dict__=<getset_descriptor at remote 0x7fffb8b687c0>, __doc__=None) at remote 0xd49ab0>, 'build': <function at remote 0x7fffb8b62af0>, 'h': <float at remote 0x7ffff773c490>, 'r': <float at remote 0x7ffff773c470>, ...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='v.py') at remote 0x7ffff7840160>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff78a70e0>, '__file__': 'v.py', '__cached__': None, 'math': <module at remote 0x7ffff774bb80>, 'EXT_OPEN': 0, 'GeometryBuilder': <type at remote 0xd1ccc0>, 'generate_surface_of_revolution': <function at remote 0x7fffb8b5dee0>, 'MeshInfo': <pybind11_type(__module__='meshpy.tet', set_facets=<function at remote 0x7fffb8b62700>, set_facets_ex=<function at remote 0x7fffb8b62790>, dump=<function at remote 0x7fffb8b62820>, write_vtk=<function at remote 0x7fffb8b628b0>, set_elements=<function at remote 0x7fffb8b62940>, set_element_constraints=<function at remote 0x7fffb8b629d0>, __dict__=<getset_descriptor at remote 0x7fffb8b687c0>, __doc__=None) at remote 0xd49ab0>, 'build': <function at remote 0x7fffb8b62af0>, 'h': <float at remote 0x7ffff773c490>, 'r': <float at remote 0x7ffff773c470>, ...(truncated)) at ../Python/pythonrun.c:1125
#37 0x00000000005e6bdf in run_mod (mod=<optimized out>, filename=<optimized out>, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='v.py') at remote 0x7ffff7840160>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff78a70e0>, '__file__': 'v.py', '__cached__': None, 'math': <module at remote 0x7ffff774bb80>, 'EXT_OPEN': 0, 'GeometryBuilder': <type at remote 0xd1ccc0>, 'generate_surface_of_revolution': <function at remote 0x7fffb8b5dee0>, 'MeshInfo': <pybind11_type(__module__='meshpy.tet', set_facets=<function at remote 0x7fffb8b62700>, set_facets_ex=<function at remote 0x7fffb8b62790>, dump=<function at remote 0x7fffb8b62820>, write_vtk=<function at remote 0x7fffb8b628b0>, set_elements=<function at remote 0x7fffb8b62940>, set_element_constraints=<function at remote 0x7fffb8b629d0>, __dict__=<getset_descriptor at remote 0x7fffb8b687c0>, __doc__=None) at remote 0xd49ab0>, 'build': <function at remote 0x7fffb8b62af0>, 'h': <float at remote 0x7ffff773c490>, 'r': <float at remote 0x7ffff773c470>, ...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='v.py') at remote 0x7ffff7840160>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff78a70e0>, '__file__': 'v.py', '__cached__': None, 'math': <module at remote 0x7ffff774bb80>, 'EXT_OPEN': 0, 'GeometryBuilder': <type at remote 0xd1ccc0>, 'generate_surface_of_revolution': <function at remote 0x7fffb8b5dee0>, 'MeshInfo': <pybind11_type(__module__='meshpy.tet', set_facets=<function at remote 0x7fffb8b62700>, set_facets_ex=<function at remote 0x7fffb8b62790>, dump=<function at remote 0x7fffb8b62820>, write_vtk=<function at remote 0x7fffb8b628b0>, set_elements=<function at remote 0x7fffb8b62940>, set_element_constraints=<function at remote 0x7fffb8b629d0>, __dict__=<getset_descriptor at remote 0x7fffb8b687c0>, __doc__=None) at remote 0xd49ab0>, 'build': <function at remote 0x7fffb8b62af0>, 'h': <float at remote 0x7ffff773c490>, 'r': <float at remote 0x7ffff773c470>, ...(truncated), flags=<optimized out>, arena=<optimized out>) at ../Python/pythonrun.c:1147
#38 0x00000000005ef537 in PyRun_FileExFlags (fp=0x923470, filename_str=<optimized out>, start=<optimized out>, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='v.py') at remote 0x7ffff7840160>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff78a70e0>, '__file__': 'v.py', '__cached__': None, 'math': <module at remote 0x7ffff774bb80>, 'EXT_OPEN': 0, 'GeometryBuilder': <type at remote 0xd1ccc0>, 'generate_surface_of_revolution': <function at remote 0x7fffb8b5dee0>, 'MeshInfo': <pybind11_type(__module__='meshpy.tet', set_facets=<function at remote 0x7fffb8b62700>, set_facets_ex=<function at remote 0x7fffb8b62790>, dump=<function at remote 0x7fffb8b62820>, write_vtk=<function at remote 0x7fffb8b628b0>, set_elements=<function at remote 0x7fffb8b62940>, set_element_constraints=<function at remote 0x7fffb8b629d0>, __dict__=<getset_descriptor at remote 0x7fffb8b687c0>, __doc__=None) at remote 0xd49ab0>, 'build': <function at remote 0x7fffb8b62af0>, 'h': <float at remote 0x7ffff773c490>, 'r': <float at remote 0x7ffff773c470>, ...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='v.py') at remote 0x7ffff7840160>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7ffff78a70e0>, '__file__': 'v.py', '__cached__': None, 'math': <module at remote 0x7ffff774bb80>, 'EXT_OPEN': 0, 'GeometryBuilder': <type at remote 0xd1ccc0>, 'generate_surface_of_revolution': <function at remote 0x7fffb8b5dee0>, 'MeshInfo': <pybind11_type(__module__='meshpy.tet', set_facets=<function at remote 0x7fffb8b62700>, set_facets_ex=<function at remote 0x7fffb8b62790>, dump=<function at remote 0x7fffb8b62820>, write_vtk=<function at remote 0x7fffb8b628b0>, set_elements=<function at remote 0x7fffb8b62940>, set_element_constraints=<function at remote 0x7fffb8b629d0>, __dict__=<getset_descriptor at remote 0x7fffb8b687c0>, __doc__=None) at remote 0xd49ab0>, 'build': <function at remote 0x7fffb8b62af0>, 'h': <float at remote 0x7ffff773c490>, 'r': <float at remote 0x7ffff773c470>, ...(truncated), closeit=1, flags=0x7fffffffe008) at ../Python/pythonrun.c:1063
#39 0x00000000005ef000 in PyRun_SimpleFileExFlags (fp=0x923470, filename=0x7ffff7840050 "v.py", closeit=1, flags=0x7fffffffe008) at ../Python/pythonrun.c:428
#40 0x00000000005e40c5 in pymain_run_file (cf=0x7fffffffe008, config=0x923850) at ../Modules/main.c:381
#41 pymain_run_python (exitcode=0x7fffffffe000) at ../Modules/main.c:606
#42 Py_RunMain () at ../Modules/main.c:685
#43 0x00000000005c29c9 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:739
#44 0x00007ffff7c27cca in __libc_start_main (main=0x5c2990 <main>, argc=2, argv=0x7fffffffe1f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe1e8) at ../csu/libc-start.c:308
#45 0x00000000005c28ca in _start () at ../Python/compile.c:999
```
My guess would be that this is a Tetgen bug, likely reproducible with just command line `tetgen`. Based on this, I'd say this is likely not a meshpy bug.

**Comment by nschloe** [comment]
Yeah, a segfault points towards C++. Not sure what to do about this since tetgen isn't an open-source project with the appropriate infrastructure (bug tracker etc.). Feel free to close it, it really isn't a meshpy bug.

**Comment by inducer** [comment]
Sounds good. Sorry about the trouble, not sure I can do much here. Thanks for understanding.
